import axios from 'axios';
// import { getUserSessionData } from '../utils/userSession';
// import { getUserConfig } from '../utils/userConfig';

// const user = getUserSessionData();
const token =
    'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjE4OTZlMjUyIn0.eyJzdWIiOiI4ZDEwZGQ4YS1hOTViLTQ5MDctODg1ZC0xODIzYjQ0ZTM3NzUiLCJuYW1lIjoiVmFuZXNzYSBUYW4iLCJlbWFpbCI6InZhbmVzc2FAbWVsaW9yLmFpIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm1ldGFkYXRhIjp7Im44bkFwaUtleSI6Im44bl9hcGlfMGYzZDJhZDM5YjFlYzhjM2IwYjIwZWY4M2I1MjhmNzBlZWYxYWEzMmU1MDQ1ZjhlNmUxNTczM2NjN2RhY2Q1MTQ3OGZlNDU1NjU5OGYyYTEiLCJsYW5ndWFnZSI6ImVuIiwic3RvcmFnZVVzZXJJZCI6IjMzNDM0NzY0NjMxIn0sInJvbGVzIjpbIlVzZXIiLCJBZG1pbiJdLCJwZXJtaXNzaW9ucyI6WyJmZS5hY2NvdW50LXNldHRpbmdzLndyaXRlLmN1c3RvbS1sb2dpbi1ib3giLCJmZS5jb25uZWN0aXZpdHkuKiIsImZlLnNlY3VyZS4qIiwiZmUuc2VjdXJlLmRlbGV0ZS50ZW5hbnRBcGlUb2tlbnMiLCJmZS5zZWN1cmUud3JpdGUudXNlckFwaVRva2VucyIsImZlLnNlY3VyZS5kZWxldGUudXNlckFwaVRva2VucyIsImZlLnNlY3VyZS5yZWFkLnRlbmFudEFwaVRva2VucyIsImZlLnNlY3VyZS53cml0ZS50ZW5hbnRBcGlUb2tlbnMiLCJmZS5zZWN1cmUucmVhZC51c2VyQXBpVG9rZW5zIiwiZmUuYWNjb3VudC1zZXR0aW5ncy5yZWFkLmFwcCJdLCJ0ZW5hbnRJZCI6IjAwMSIsInRlbmFudElkcyI6WyIwMDEiXSwicHJvZmlsZVBpY3R1cmVVcmwiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NKalNpU1czcVd2NTRtWm04NkM1LTFURjlqaGVBQVpaLXFhNUV2eUJycFNmelRITlE9czk2LWMiLCJzaWQiOiIzMTA4ZTI0Ni1kOGUxLTQxNTQtYWEyMS0wMmU0ZWYyODY0ZmQiLCJ0eXBlIjoidXNlclRva2VuIiwiYXBwbGljYXRpb25JZCI6IjY0ZTYwOWFiLWNkYTAtNDUwYy04NjYzLTAxNGU2NjI4MWFmMSIsImF1ZCI6IjE4OTZlMjUyLTI2YTQtNDI4OS1hZjYwLTQ1YWJmOTI3NmExZCIsImlzcyI6Imh0dHBzOi8vZGV2LmNpbnQubWVsaW9yLmFpIiwiaWF0IjoxNzE1MjIwOTIzLCJleHAiOjE3MTUzMDczMjN9.IPfnUXxD3-WUQ0gp6ZQg644Thujrgdqz4rP-PYccXaY-4kQ1gy6nHYA7gK90BSdE2vfJiaHEaf5a3pYHuiwyjuKnTTRoNP2xJtSrVUk7JxSCpMtn5MNK5eVv4vokieYkO56SY31OC8843mx5yhdt7Pr6Gfufa3uVZoYtkolNLvY0_cPLpzOfHo4-_QmNcB9x17zfCY60P7DxbWaris9j849CtXYAohfNV7jkFNTcH3lJyWkAEFm28Er00eCzIK9lxramzRRLWkchCfjEv0Y27zk0UjWM_1VwPtmCccEQ-NqSh96YQuERJQihO4QL6LLdjiyT7qbU9K1JuKSosXb9tQ';
const backendAPIClient = axios.create();

const interceptor = (config) => {
    // const backendBaseURL = getUserConfig()?.backendBaseUrl;
    const backendBaseURL = 'https://dev.api.eu.melior.ai/v5.0/';
    config.baseURL = backendBaseURL ? backendBaseURL : config.baseURL;
    // config.headers.Authorization = `Bearer ${user?.accessToken}`;
    config.headers.Authorization = `Bearer ${token}`;
    return config;
};

backendAPIClient.interceptors.request.use(interceptor);

export default backendAPIClient;
